from copy import deepcopy

from .base import BaseAttack


class ChannelManipulationAttack(BaseAttack):

    SUPPORTED_TYPES = {
        "bit_flip",
        "phase_flip",
        "depolarizing"
    }

    def __init__(
        self,
        manipulation_type="bit_flip",
        probability=0.1
    ):

        if manipulation_type not in self.SUPPORTED_TYPES:
            raise ValueError(
                f"Unsupported manipulation type: "
                f"{manipulation_type}"
            )

        if not 0 <= probability <= 1:
            raise ValueError(
                "probability must be between 0 and 1"
            )

        self.manipulation_type = manipulation_type
        self.probability = probability

    def apply(self, experiment_data: dict) -> dict:

        attacked_data = deepcopy(experiment_data)

        # Use the real measurement counts produced by P1.
        counts = attacked_data["measurement_counts"].copy()

        total = sum(counts.values())

        if total == 0:
            return attacked_data

        # Find the state that P1 measured most frequently.
        expected_state = max(
            counts,
            key=counts.get
        )

        # Number of P1 measurements to manipulate.
        manipulated = int(
            total * self.probability
        )

        manipulated = min(
            counts[expected_state],
            manipulated
        )

        # Select where manipulated measurements are moved.
        if self.manipulation_type == "bit_flip":

            target_state = (
                "11"
                if expected_state != "11"
                else "00"
            )

        elif self.manipulation_type == "phase_flip":

            target_state = (
                "01"
                if expected_state != "01"
                else "10"
            )

        else:  # depolarizing

            other_states = [
                state
                for state in counts
                if state != expected_state
            ]

            target_state = other_states[0]

        # P3 modifies the actual counts generated by P1.
        counts[expected_state] -= manipulated

        counts[target_state] += manipulated

        # Store attacked data for P2 detection.
        attacked_data["measurement_counts"] = counts

        attacked_data["attack_type"] = (
            "channel_manipulation"
        )

        attacked_data["channel_attack"] = {
            "enabled": True,
            "type": self.manipulation_type,
            "probability": self.probability
        }

        attacked_data["attack_metadata"] = {
            "channel_manipulation_type":
                self.manipulation_type,

            "probability":
                self.probability,

            "original_state":
                expected_state,

            "target_state":
                target_state,

            "manipulated_measurements":
                manipulated
        }

        return attacked_data